import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const clients = [
    {
      nombreCompleto: "Yolanda Cayetano Arriague",
      ci: "5072251",
      extension: "PT",
      email: "cayetanoyolanda70@gmail.com",
      celular: "73877279",
      profesion: "Maestra de Comunicación y Lenguaje",
      direccion: "Av. Bolivia Nro 12",
      fechaNacimiento: "1970-05-15",
      pideLibros: false,
      cantLibros: 0,
      pideArticulos: false,
      cantArticulos: 0,
      pideDirector: false,
      pideFundador: true,
      notasServicio: "Fundadora de la revista",
      status: "procesado",
    },
    {
      nombreCompleto: "Grover Carvajal Yavincha",
      ci: "",
      extension: "",
      email: "carvajalgrover78@gmail.com",
      celular: "68238846",
      profesion: "Maestro de Técnica Tecnológica Especializada Electricidad Industrial",
      direccion: "",
      fechaNacimiento: "",
      pideLibros: false,
      cantLibros: 0,
      pideArticulos: true,
      cantArticulos: 3,
      pideDirector: false,
      pideFundador: false,
      notasServicio: "",
      status: "en proceso",
    },
    {
      nombreCompleto: "Yeyi Magui Hurtado Mamani",
      ci: "6464368",
      extension: "CB",
      email: "infomagui7@gmail.com",
      celular: "67460516",
      profesion: "Maestra de Matemática Educación Secundaria Comunitaria Productiva",
      direccion: "Calle Sucre Nro 45",
      fechaNacimiento: "1985-03-22",
      pideLibros: false,
      cantLibros: 0,
      pideArticulos: true,
      cantArticulos: 5,
      pideDirector: false,
      pideFundador: false,
      notasServicio: "",
      status: "formulario llenado",
    },
    {
      nombreCompleto: "Reina Isabel Mamani Mamani",
      ci: "3548338",
      extension: "OR",
      email: "reinaisabelmamani34@gmail.com",
      celular: "71661418",
      profesion: "Maestra de Educación Primaria Comunitaria Vocacional",
      direccion: "Av. 6 de Agosto Nro 8",
      fechaNacimiento: "1980-11-03",
      pideLibros: false,
      cantLibros: 0,
      pideArticulos: true,
      cantArticulos: 1,
      pideDirector: false,
      pideFundador: false,
      notasServicio: "",
      status: "formulario llenado",
    },
    {
      nombreCompleto: "Felix Omar Mamani Mamani",
      ci: "6245791",
      extension: "ST",
      email: "felix901mamani@gmail.com",
      celular: "68789424",
      profesion: "Ciencias Sociales",
      direccion: "",
      fechaNacimiento: "",
      pideLibros: false,
      cantLibros: 0,
      pideArticulos: true,
      cantArticulos: 1,
      pideDirector: false,
      pideFundador: false,
      notasServicio: "",
      status: "formulario llenado",
    },
    {
      nombreCompleto: "Ingrid Melfy Zuna Calle",
      ci: "7723936",
      extension: "ST",
      email: "ingridzuna@gmail.com",
      celular: "69013436",
      profesion: "Comunicación y Lenguaje: Lengua Castellana y Originaria",
      direccion: "",
      fechaNacimiento: "",
      pideLibros: false,
      cantLibros: 0,
      pideArticulos: true,
      cantArticulos: 1,
      pideDirector: false,
      pideFundador: false,
      notasServicio: "",
      status: "formulario llenado",
    },
    {
      nombreCompleto: "Carlos Eduardo Quispe Flores",
      ci: "4123456",
      extension: "LP",
      email: "carlosquispe@gmail.com",
      celular: "72345678",
      profesion: "Maestro de Física",
      direccion: "Calle Murillo Nro 23",
      fechaNacimiento: "1978-07-10",
      pideLibros: true,
      cantLibros: 2,
      pideArticulos: true,
      cantArticulos: 2,
      pideDirector: false,
      pideFundador: false,
      notasServicio: "Quiere 2 libros y 2 artículos",
      status: "pendiente",
    },
    {
      nombreCompleto: "Maria Elena Condori Apaza",
      ci: "5987654",
      extension: "OR",
      email: "mariacondori@gmail.com",
      celular: "71987654",
      profesion: "Maestra de Biología",
      direccion: "Av. Antofagasta Nro 15",
      fechaNacimiento: "1990-02-28",
      pideLibros: true,
      cantLibros: 1,
      pideArticulos: false,
      cantArticulos: 0,
      pideDirector: true,
      pideFundador: false,
      notasServicio: "Quiere ser directora de revista",
      status: "en proceso",
    },
  ];

  for (const c of clients) {
    const token = Math.random().toString(36).substring(2) +
      Math.random().toString(36).substring(2);

    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + 4);

    await prisma.client.create({
      data: {
        token,
        expiresAt,
        ...c,
      },
    });
  }

  console.log("✅ Clientes de prueba creados");
}

main().finally(() => prisma.$disconnect());